export const input = <>
    <table>
        <tgroup
            columns={[
                {},
                {},
                {},
            ]}
            >
            <thead>
                <row>
                    <cell><p>h1</p></cell>
                    <cell><p>h2</p></cell>
                    <cell><p>h3</p></cell>
                </row>
            </thead>
            <row>
                <cell><p>r1-1</p></cell>
                <cell><p>r1-2</p></cell>
                <cell><p>r1-3</p></cell>
            </row>
            <row>
                <cell><p>r2-1</p></cell>
                <cell><p>r2-2</p></cell>
                <cell><p>r2-3</p></cell>
            </row>
            <tfoot>
                <row>
                    <cell><p>f1</p></cell>
                    <cell><p>f2</p></cell>
                    <cell><p>f3</p></cell>
                </row>
            </tfoot>
        </tgroup>
        <tablesummary>Table summary</tablesummary>
    </table>
</>

export const output = cnxml`
<table summary="Table summary">
    <tgroup cols="3">
        <thead>
            <row>
                <entry><para>h1</para></entry>
                <entry><para>h2</para></entry>
                <entry><para>h3</para></entry>
            </row>
        </thead>
        <tfoot>
            <row>
                <entry><para>f1</para></entry>
                <entry><para>f2</para></entry>
                <entry><para>f3</para></entry>
            </row>
        </tfoot>
        <tbody>
            <row>
                <entry><para>r1-1</para></entry>
                <entry><para>r1-2</para></entry>
                <entry><para>r1-3</para></entry>
            </row>
            <row>
                <entry><para>r2-1</para></entry>
                <entry><para>r2-2</para></entry>
                <entry><para>r2-3</para></entry>
            </row>
        </tbody>
    </tgroup>
</table>
`
